### PR TITLE
RFCs mdbook

### PR DESCRIPTION
**Pull request by thibault-martinez**

### CODE REVIEW

**Comment by nothingismagick** [comment]
Wish this would make a PDF too.

**Comment by Wollac** [comment]
Are there configuration options to closer match the IOTA design styles?

**Comment by thibault-martinez** [comment]
Are you speaking about `no-section-label` ? By default mdbook creates sections labels (1.1, 1.2, ...) but it makes no sense for RFCs.

**Comment by Wollac** [comment]
No, I was more thinking about adding the IOTA logo or using the color palette to make it closer to existing iota.org websites.

**Comment by thibault-martinez** [comment]
Ahhh, I'm sure we can change the theme yes.
I can have a look at that later :)
https://rust-lang.github.io/mdBook/format/config.html

**Comment by Wollac** [comment]
We can add custom styles later. I've created an issue for it so that we don't forget it.

**Pull request merged**
